# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AI-modules',
                'doc_host': 'https://LeeviEnontekio.github.io',
                'git_url': 'https://github.com/LeeviEnontekio/AI-modules',
                'lib_path': 'AI_modules'},
  'syms': {'AI_modules.core': {'AI_modules.core.foo': ('core.html#foo', 'AI_modules/core.py')}}}
